### ISSUE TITLE
"error: 'QuerySet' object has no attribute 'random'"

### ISSUE THREAD

**Issue by xporium** [rremizov/django-random-queryset#3]
hi,
if  i use filter than i can get "'QuerySet' object has no attribute 'random" error.

queryset = models.Visitor.objects.filter(user_id__in=ids)               
 queryset.random()  # to get one random record

if use queryset = models.Visitor.objects.random(1) its working fine but i want filter also..

Please tell me how to resolve this

thanks

**Comment by rremizov** [comment]
Indeed, `.filter().random()` didn't work on Django>=2.0.
The new version (0.1.1) is on PyPI, let me know if you run into any issues.
